version: '3'
services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_authentication_example
    ports:
      - '5432:5432'
  authentication_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    links:
      - database


volumes:
  postgres-data:
    driver: local